version: "2.4"

services:
    spark-2.4.7-2.12:
        image: datamechanics/spark:jvm-only-2.4.7-latest
        command: /opt/spark/bin/spark-submit --class org.apache.spark.examples.SparkPi --master 'local[2]' --jars /opt/spark/delight.jar --conf spark.extraListeners=co.datamechanics.delight.DelightListener $EXTRA_OPTS /opt/spark/examples/jars/spark-examples_2.12-2.4.7.jar 100
        volumes:
            - ./target/scala-2.12/delight_2.12-latest-SNAPSHOT.jar:/opt/spark/delight.jar
        env_file:
            - .env

    spark-2.4.7-2.11:
        image: datamechanics/spark:jvm-only-2.4.7-hadoop-3.1.0-java-8-scala-2.11-latest
        command: /opt/spark/bin/spark-submit --class org.apache.spark.examples.SparkPi --master 'local[2]' --jars /opt/spark/delight.jar --conf spark.extraListeners=co.datamechanics.delight.DelightListener $EXTRA_OPTS /opt/spark/examples/jars/spark-examples_2.11-2.4.7.jar 100
        volumes:
            - ./target/scala-2.11/delight_2.11-latest-SNAPSHOT.jar:/opt/spark/delight.jar
        env_file:
            - .env

    spark-3.0.1-2.12:
        image: datamechanics/spark:jvm-only-3.0.1-latest
        command: /opt/spark/bin/spark-submit --class org.apache.spark.examples.SparkPi --master 'local[2]' --jars /opt/spark/delight.jar --conf spark.extraListeners=co.datamechanics.delight.DelightListener $EXTRA_OPTS /opt/spark/examples/jars/spark-examples_2.12-3.0.1.jar 100
        volumes:
            - ./target/scala-2.12/delight_2.12-latest-SNAPSHOT.jar:/opt/spark/delight.jar
        env_file:
            - .env

    spark-3.1.1-2.12:
        image: datamechanics/spark:jvm-only-3.1.1-latest
        command: /opt/spark/bin/spark-submit --class org.apache.spark.examples.SparkPi --master 'local[2]' --jars /opt/spark/delight.jar --conf spark.extraListeners=co.datamechanics.delight.DelightListener $EXTRA_OPTS /opt/spark/examples/jars/spark-examples_2.12-3.1.1.jar 100
        volumes:
            - ./target/scala-2.12/delight_2.12-latest-SNAPSHOT.jar:/opt/spark/delight.jar
        env_file:
            - .env